### ISSUE TITLE
Unable to run python script with code (simplecv console OKAY) - Exception in thread Thread-2 (most likely raised during interpreter shutdown)

### ISSUE THREAD

**Issue by kevinng** [sightmachine/SimpleCV#206]
Hi,

I'm trying out the first example in the simplecv book, and I'm having some problem running the example executing from the python file (i.e. python helloworld.py). However, copying and pasting the code into the simplecv console work. On exiting the console, I have the same error message as when I tried to execute my example from the file.
## Error message:

Exception in thread Thread-2 (most likely raised during interpreter shutdown)

My code:

``` python
from SimpleCV import Camera, Display, Image
cam = Camera()
display = Display()
img = cam.getImage()
img.save(display)
```

**Comment by am-sirdaniel** [comment]
thats bad

**Comment by am-sirdaniel** [comment]
you cant remember
