### ISSUE TITLE
Ubuntu package: can't find SimpleCV logo

### ISSUE THREAD

**Issue by takluyver** [sightmachine/SimpleCV#213]
I don't know if this is the correct place to report this - please point me in the right direction if not.

I've just installed the .deb package for SimpleCV on Ubuntu 12.04. When I try to show any image, I get the traceback pasted below. I assume this is just trouble with the packaging, as it's not finding the logo in the directory where it expects it.

```
SimpleCV:10> img.show()
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
/usr/lib/pymodules/python2.7/SimpleCV/Shell/Shell.pyc in <module>()
----> 1 img.show()

/usr/lib/pymodules/python2.7/SimpleCV/ImageClass.pyc in show(self, type)
   5445               d = Display(displaytype='notebook')
   5446           else:
-> 5447               d = Display(self.size())
   5448           self.save(d)
   5449           return d

/usr/lib/pymodules/python2.7/SimpleCV/Display.pyc in __init__(self, resolution, flags, title, displaytype, headless)
    156         if not displaytype == 'notebook':
    157             self.screen = pg.display.set_mode(resolution, flags)
--> 158         scvLogo = SimpleCV.Image("simplecv").scale(32,32)
    159         pg.display.set_icon(scvLogo.getPGSurface())
    160         if flags != pg.FULLSCREEN and flags != pg.NOFRAME:

/usr/lib/pymodules/python2.7/SimpleCV/ImageClass.pyc in __init__(self, source, camera, colorSpace, verbose, sample, cv2image)
    785                     self._bitmap = cv.LoadImage(self.filename, iscolor=cv.CV_LOAD_IMAGE_COLOR)
    786                 except:
--> 787                     self._pil = pil.open(self.filename).convert("RGB")
    788                     self._bitmap = cv.CreateImageHeader(self._pil.size, cv.IPL_DEPTH_8U, 3)
    789                     cv.SetData(self._bitmap, self._pil.tostring())

/usr/lib/python2.7/dist-packages/PIL/Image.pyc in open(fp, mode)
   1950         import __builtin__
   1951         filename = fp
-> 1952         fp = __builtin__.open(fp, "rb")
   1953     else:
   1954         filename = ""

IOError: [Errno 2] No such file or directory: '/usr/lib/pymodules/python2.7/SimpleCV/sampleimages/simplecv.png'
```

**Comment by Petertoo** [comment]
I have just installed ubuntu and simpleCV today. I am having the same problem. In fact, if I try to view any image it gives me this error, irrispective of the location of the image. Why it is looking in this directory I do not know. It doesn't even exist. It SEEMS to me that there is a big chunk of simpleCV that just doesn't work.

**Comment by kumarankit2594** [comment]
Could you upload your code?

**Comment by Petertoo** [comment]
Hi Ankit

 

So, in simplecv, Ubuntu running in VirtualBox. I find it cannot find an image that is not in the current directory, so I change directory first. Also, it needs the file type to see an image (so, mark.png, not just mark). Not a problem, just explaining why I have done certain things.

 

cd /home/peter/Downloads

testimage = Image(“mark.png”)

testimage.show()

 

Then I get the error message, see attached screen capture (I also attach mark.png for you to see). Out of curiosity, if I navigate to the file referred to in the error, I find the containing directory is not there. Anyway, why is it trying to see the simplecv.png logo when I am looking at mark.png in the current directory. By the way, I can save testimage and view it with a normal picture viewer.

 

Thanks

 

Peter

**Comment by kumarankit2594** [comment]
Hi Petertoo

Just try to give full path of your mark.png(something like:-  "G:/images/mark.png"). If this does not work than there must be something wrong with your Ubuntu or SimpleCV installation, i am not sure because i am running SimpleCV in my 64 bit windows 10 system. So, i would suggest you to first go for above mentioned full path of your image.

**Comment by hedingjie** [comment]
I use Ubuntu15. And i just 'mkdir' the /usr/lib/pymodules/python2.7/SimpleCV/sampleimages/, and copy the 'simplecv.png' to it. It works!

**Comment by checor** [comment]
I use Manjaro (Arch fork). Oddly enough, I installed from AUR and this issue was present.
Copying the image also solves the problem.

Thanks!

**Comment by Petertoo** [comment]
I Gave up. I used numpy and did a least mean square error. Takes longer, but gives a more reliable result so I am told. Obviously doesn’t work in real world photos (perspective…).

**Comment by checor** [comment]
Hi Petertoo, I had the same problem, try to do the same that vijaym123. Copy the sample picture to that directory with root parameters.

I still wonder why looks for that photo even if you tell the program to load another picture.

Cheers.
