### ISSUE TITLE
ORB Keypoint detection always returns 500 keypoints when matching, but other "flavors" vary.

### ISSUE THREAD

**Issue by xamox** [sightmachine/SimpleCV#301]
It appears that is the default to the ORB constructor.  I'm not if it possible using the python interface to change this or not.  I know that cv2.ORB exist, but we are using 

``` python
fd = cv2.FeatureDetector_create("ORB")
descriptor = cv2.DescriptorExtractor_create("ORB")

keypoints = detector.detect(img)
keypoints, sd = descriptor.compute(img, keypoints)
```

Maybe Jay knows why this is.

**Comment by cybersupernova** [comment]
You can change the default value by just passing the argument while creating object like so

`cv2.ORB(nfeatures=1000)`

however, creating an object like above does not work in version 3. You can do that like

`cv2.ORB_create(nfeatures=5000)`
