### ISSUE TITLE
Display.py opens non-existing simplecv.png

### ISSUE THREAD

**Issue by hadzibanov-kostadin** [sightmachine/SimpleCV#466]
I had an issue when setting up a display or running the show() method on an Image. The display class tries to open "simplecv.png" when initialising even if there is no "sampleimages" folder. I downloaded SimpleCV from SourceForge and the Ubuntu store, which hosted the version without sample images, however I noticed the faulty code is the same in the Github repository. Should I try and make a fix?

Here is the stack trace:

<pre><code>
SimpleCV:9> display()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/usr/lib/pymodules/python2.7/SimpleCV/Shell/Shell.pyc in <module>()
----> 1 display()

NameError: name 'display' is not defined

SimpleCV:10> disp=Display()
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
/usr/lib/pymodules/python2.7/SimpleCV/Shell/Shell.pyc in <module>()
----> 1 disp=Display()

/usr/lib/pymodules/python2.7/SimpleCV/Display.pyc in __init__(self, resolution, flags, title, displaytype, headless)
    156         if not displaytype == 'notebook':
    157             self.screen = pg.display.set_mode(resolution, flags)
--> 158         scvLogo = SimpleCV.Image("simplecv").scale(32,32)
    159         pg.display.set_icon(scvLogo.getPGSurface())
    160         if flags != pg.FULLSCREEN and flags != pg.NOFRAME:

/usr/lib/pymodules/python2.7/SimpleCV/ImageClass.pyc in __init__(self, source, camera, colorSpace, verbose, sample, cv2image)
    785                     self._bitmap = cv.LoadImage(self.filename, iscolor=cv.CV_LOAD_IMAGE_COLOR)
    786                 except:
--> 787                     self._pil = pil.open(self.filename).convert("RGB")
    788                     self._bitmap = cv.CreateImageHeader(self._pil.size, cv.IPL_DEPTH_8U, 3)
    789                     cv.SetData(self._bitmap, self._pil.tostring())

/usr/lib/python2.7/dist-packages/PIL/Image.pyc in open(fp, mode)
   1950         import __builtin__
   1951         filename = fp
-> 1952         fp = __builtin__.open(fp, "rb")
   1953     else:
   1954         filename = ""

IOError: [Errno 2] No such file or directory: '/usr/lib/pymodules/python2.7/SimpleCV/sampleimages/simplecv.png'
</code></pre>

**Comment by sly74fr** [comment]
Still the same from Ubuntu 14.04LTS !!
