### ISSUE TITLE
Installation for Raspberry Pi Broken

### ISSUE THREAD

**Issue by tony72** [sightmachine/SimpleCV#579]
Since the addition of the required dependency svgwrite in setup.py, SimpleCV no longer works on Raspberry Pi. The library svgwrite does not get pulled in with the dependencies for SimpleCV, so the installation instructions are no longer valid. Also there is no mention that svgwrite is now a requirement. With a long Google search I cannot even find svgwrite to install it. You need to either remove the requirement, fix the installation to include the svgwrite dependency, or at least let people know that it is now a requirement and how to get it. I am going to guess this would be true for any version of Debian Linux that someone would want to run SimpleCV on.

**Comment by sroller** [comment]
I'm trying to follow the installation.
I'm on Raspbian Jessie.
The documentation for the Raspberry PI installation seems out of date.
The requirements.txt contains "PIL" which can't be found by pip.
I can start ipython.
I did "import cv2", no error was giving.
```python
print cv2.version
    AttributeError: 'module' object has no attribute 'version'
```
I'm running python 2.7.9
