### ISSUE TITLE
Error installing PIL on raspberry pi

### ISSUE THREAD

**Issue by theonlyjames** [sightmachine/SimpleCV#686]
> pip install PIL

Downloading/unpacking PIL
  Could not find any downloads that satisfy the requirement PIL  
  Some externally hosted files were ignored (use --allow-external PIL to allow). 
Cleaning up... 
No distributions at all found for PIL 
Storing debug log for failure in /root/.pip/pip.log 

> pip uninstall PIL
> Can't uninstall 'PIL'. No files were found to uninstall.

I got this error but it has been resolved in the following link

http://stackoverflow.com/questions/21242107/pip-install-pil-dont-install-into-virtualenv

fix: 

pip install PIL --allow-external

**Comment by golyalpha** [comment]
Well, there is a suggestion to use --allow-external switch, in the console output, you could do that, and if it would fail, you would follow another suggestion, that would surely say something along the lines of "use --allow-unverified to install this package". I'm really surprised that that question doesn't have like -100 votes up on StackOverflow, but I guess it's the world we live in, where dumb questions, solved by just reading the screen are upvoted, and actual questions, that are not as easily solved are downvoted...

By the way, close this issue, if it's solved.
