### ISSUE TITLE
sampleimages folder not being added in dist-packages

### ISSUE THREAD

**Issue by jayrambhia** [sightmachine/SimpleCV#88]
I downloaded SimpleCV from GitHub just now. I installed it

```
sudo python setup.py install
```

I tried

```
i = Image("simplecv")
```

I am getting error

```
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/SimpleCV-1.2-py2.7.egg/SimpleCV/sampleimages/simplecv.png'
```

sampleimages folder is not there in **/usr/local/lib/python2.7/dist-packages/SimpleCV-1.2-py2.7.egg/SimpleCV**
So, I looked at setup.py file, I couldn't find any problems.

```
package_data  = { #DO NOT REMOVE, NEEDED TO LOAD INLINE FILES i = Image('simplecv')
        'SimpleCV': ['sampleimages/*'],
        'SimpleCV':['Features/HaarCascades/*'],
```

HaarCascades are there but not sampleimages.

I tried re-installing SimpleCV from source that I had downloaded couple of weeks back. It's setup file includes only sampleimages.

```
package_data  = { #DO NOT REMOVE, NEEDED TO LOAD INLINE IMAGES
        'SimpleCV': ['sampleimages/*']
```

After installing from old version, I can access sampleimages

```
i = Image("simplecv")
```

Installed SimpleCV-e7665f5 >  http://bpaste.net/show/28462/  
Installed SimpleCV-3fea5c1 > http://bpaste.net/show/mcMUp9gjCWoWTvB5EBzX/

**Comment by powderblock** [comment]
More than three years later and still going strong.

**Comment by DavidAwad** [comment]
I just got this bug again after a pip install. Really simple fix is just to copy it in from the repo but I'm not really sure why it's not there in the first place : /
