### ISSUE TITLE
VirtualCamera Image issue

### ISSUE THREAD

**Issue by anjiro** [sightmachine/SimpleCV#96]
SimpleCV 1.2.0 on OSX 10.7 - installed from source about 2 hours ago.

The basic issue is that Images pulled from a video source show as the same image in some circumstances:

``` python
from SimpleCV import *
from numpy import array_equal

c = VirtualCamera('/tmp/test.mov', 'video')
a = c.getImage()
for i in xrange(20):
    b = c.getImage()

a.show()
b.show()  #they look different

a.sideBySide(b).show()  #shows the same image

(a-b).show()  #black

na = a.getNumpy()
nb = b.getNumpy()

array_equal(na, nb)  #True
```

**Comment by diomarsonlarin** [comment]
@anjiro sir may i ask where should i put the video? i was trying to access a video and capture a frame in it at a certain time.

this is what i found that can use videos for static data files. 
vidcam = VirtualCamera("bananas.mpg", "video")
imgcam.getImage().save("frame_1_of_bananas.jpg")
